### ISSUE TITLE
Paid support

### ISSUE THREAD

**Issue by nsmith1024** [juanrmn/Arduino-Telescope-Control#4]
Hello,

I was wondering if i can pay you to help me with a project like this one? Moving camera to star using stellarium, motor, and arduino.

Please contact me at iosdev1024@yahoo.com

Thanks

**Comment by juanrmn** [comment]
Hi @nsmith1024 , sorry for the delay in the response, I totally missed this.

About your request, I'm currently working full-time and I don't have time enough for this, I'm sorry.

**Comment by Bjelko** [comment]
> Hello,
> 
> I was wondering if i can pay you to help me with a project like this one? Moving camera to star using stellarium, motor, and arduino.
> 
> Please contact me at [iosdev1024@yahoo.com](mailto:iosdev1024@yahoo.com)
> 
> Thanks

Maybe  try OnStep. Functional with Mega2560+Ramps 1.4 or Wemos R32+CNC shield and some more mini "CPUs". 
@juanrmn  apologize for aiming people to another project
